checkpoint_frequency: null
data_dir: data/
dataset: WikiText2
epochs: 5
learning_rate: 1.0
model_dir: weights/cbow_50_1.0
model_name: cbow
optimizer: Adam
shuffle: true
train_batch_size: 50
train_steps: null
val_batch_size: 96
val_steps: null
